# Generated by Django 5.2.5 on 2025-08-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("totalreviews", models.IntegerField()),
                ("Rating", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
